# [`pandas.DataFrame`を読み込む](https://www.tensorflow.org/tutorials/load_data/pandas_dataframe)

ここではCleveland Clinic Foundationが提供している心臓病に関するデータセットを使う。数百のレコードがCSVに保存されており、各行は一人一人の患者を示しており、各列は要素を示している。これらの情報を利用して患者が心臓病を患っているかを判定する。

In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv')

In [3]:
df = pd.read_csv(csv_file)

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [5]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

`thal`列を離散整数値に変換する。

In [6]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

`tf.data.Dataset.from_tensor_slices`を使ってデータフレームを読み込む。`tf.data.Dataset`を使うことで、簡単で効率的なデータパイプラインを書くことができる。

In [7]:
target = df.pop('target')
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))
for feat, targ in dataset.take(5):
    print('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


`pd.Series`は`__array__`プロトコルを実装しているので、`np.array`や`tf.Tensor`を使うときに自明に使うことができる。

In [8]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

データセットのバッチとシャッフルを行う。

In [9]:
train_dataset = dataset.shuffle(len(df)).batch(1)

モデルの構築と学習

In [10]:
def get_compiled_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(1)
    ])
    
    model.compile(
        optimizer='adam',
        loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
        metrics=['accuracy']
    )
    
    return model

In [12]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15
303/303 [==============================] - 1s 619us/step - loss: 4.2867 - accuracy: 0.5576
Epoch 2/15
303/303 [==============================] - 0s 632us/step - loss: 0.8620 - accuracy: 0.7188
Epoch 3/15
303/303 [==============================] - 0s 646us/step - loss: 1.1217 - accuracy: 0.6943
Epoch 4/15
303/303 [==============================] - 0s 678us/step - loss: 0.5977 - accuracy: 0.7735
Epoch 5/15
303/303 [==============================] - 0s 734us/step - loss: 0.8737 - accuracy: 0.7064
Epoch 6/15
303/303 [==============================] - 0s 740us/step - loss: 1.5533 - accuracy: 0.6727
Epoch 7/15
303/303 [==============================] - 0s 745us/step - loss: 0.9169 - accuracy: 0.7647
Epoch 8/15
303/303 [==============================] - 0s 759us/step - loss: 0.7790 - accuracy: 0.7766
Epoch 9/15
303/303 [==============================] - 0s 799us/step - loss: 0.7631 - accuracy: 0.7619
Epoch 10/15
303/303 [==============================] - 0s 751us/step - loss: 0.746

各列を特徴づけるときに、`tf.keras.layers.Input`層の辞書を作成することと入力として辞書をモデルに渡すことは同じぐらい簡単。

In [13]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(
    optimizer='adam',
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=['accuracy']
)

`tf.data`を使ったときに`pd.DataFrame`の構造を保存するのに最も簡単な方法は、`pd.DataFrame`を`dict`に変換して、その辞書をスライスする。

In [15]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

for dict_slice in dict_slices.take(1):
    print(dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [16]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 0s 1ms/step - loss: 15.1095 - accuracy: 0.7481
Epoch 2/15
19/19 [==============================] - 0s 1ms/step - loss: 8.0518 - accuracy: 0.6168
Epoch 3/15
19/19 [==============================] - 0s 1ms/step - loss: 7.1876 - accuracy: 0.4925
Epoch 4/15
19/19 [==============================] - 0s 1ms/step - loss: 5.9335 - accuracy: 0.5527
Epoch 5/15
19/19 [==============================] - 0s 1ms/step - loss: 4.9116 - accuracy: 0.5233
Epoch 6/15
19/19 [==============================] - 0s 1ms/step - loss: 3.9485 - accuracy: 0.5044
Epoch 7/15
19/19 [==============================] - 0s 1ms/step - loss: 3.4825 - accuracy: 0.5071
Epoch 8/15
19/19 [==============================] - 0s 1ms/step - loss: 3.2184 - accuracy: 0.5450
Epoch 9/15
19/19 [==============================] - 0s 1ms/step - loss: 2.9948 - accuracy: 0.5527
Epoch 10/15
19/19 [==============================] - 0s 1ms/step - loss: 2.7973 - accuracy: 0.5604
Epoch 11/15
19/19 